---
language: node_js
node_js:
- '0.10'
services:
- neo4j
before_script:
- npm install -g grunt-cli
addons:
  sauce_connect: true
deploy:
  provider: heroku
  app: agilejs-scrumbags
  strategy: git
  api_key:
    secure: ! 'VpfKmKrG017cn4SGMxVtpIjDSGMKK3SuDJ8VrGEMbJQD20sn6M0rJ1TUe4Rl

      pMLa5a0SuPX+3BUOAgcjgDeR3eUly8KCCebYcrjrCIb/cWP2mOkwYvZmnzka

      iZWQGOgyy4MxBJ7PL+PDeQ+hWt41LYXm1GwBKT5qfs72UQgeXd8='
env:
  global:
  - secure: DsCxyubcJX02Ph3084QGGoDG8MLjaYvmdf0Xvz4Y1s4Uqn57UQZfQ798M+Vop35cnLF1VNOn78wn1VwSef6SkVHkYLcteykCNlo5l0pkbeJZgWa43I738HyPBbmVWKwDnvwweJVAd9k93VvO+ktC6aGYdYSxvCJG/GTQqedJ0ok=
  - secure: W4HKxmBub27c8wbvNdM5Ib8u4juXimGQT3Ha6YxWWD7flrH/Vq60xCv+A6LXDIsur7LKCibp/6SGKrLxg1gcLHgfrk8PVgEs1eqmnc4T/T/eTReia2Y+pI8i/tgy4cjOTtpxSTTKNfbdtJR4K4JJQtFWUzx+hs7gYEIQvKVW33w=
